### ISSUE TITLE
Active transition on hover

### ISSUE THREAD

**Issue by sandrin4p** [alexk111/SVG-Morpheus#13]
Hey, i have 3 svg and i want that the transition happens only when i hover the svg and stops on mouseleave. 
Can you help me?

If its possible, I want that when I hover it again, the transition continues where it was before. 

Thanks,
Sandrina Pereira

**Comment by ivopivo72** [comment]
+1

**Comment by wollsale** [comment]
Yo !

You've probably resolve your problem since June, but I've just red your answer and I'm currently using SVG-Morpheus on a "button hover effect".

Here is my codepen : http://codepen.io/wollsale/pen/mepREp

SVG
   > - g#see
   > - g#arrow

JAVSCRIPT
   > - var myIcons
   > - 2 functions : morphIn & morphOut (250ms, no-rotation)
   > - OnMouseEnter = morphIn
   > - OnMouseLeave = morphOut


It's probably not the best way to use it, but it work perfectly for me,

Hope it will help you,

Alexis.

**Comment by alexk111** [comment]
@wollsale Works like a charm! Thank you for providing the example dude!
